
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: second-vnic
  namespace: rock-demo-routing
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "nsx",                                         
    "networkID": "K8SC1_Second_VNIC",   
    "ipam": {                                              
      "subnet": "172.33.0.0/24",
      "rangeStart": "172.33.0.2",                          
      "rangeEnd": "172.33.0.254",
      "gateway": "172.33.0.1"
    }
}'

====
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: k8c1-vlan-nic
  namespace: rock-demo-routing
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "nsx",
    "networkID": "K8C1_VLAN_NIC", 
    "ipam": {
      "subnet": "192.168.30.0/24",
      "rangeStart": "192.168.30.80",
      "rangeEnd": "192.168.30.90",
      "gateway": "192.168.30.250"
    }
}'
